#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="nvim,tmux,zsh,git,kitty,i3-desktop"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
