#!/usr/bin/env zsh
# From the primeagen's stow video
# https://youtu.be/tkUllCAGs3c
# Smart symlinks with minimal distance
# $STOW_FOLDERS specifies which folders to install, these are set in OS specific install scripts
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
  stow -D $folder
  stow $folder
done
popd
