#!/usr/bin/env zsh

#brew install stow rg nvim bat


if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="nvim,zsh,git"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
